git-helper: fix `remote` making repos shallow
bug introduced in 6c9e339aa77d880781becd4f1b104a0a82cd10c9 which shouldn't have been an issue, but turns out providing a depth discards `--dry-run`

once unshallowed, this undoes the need for the prior rebase workaround from 1deb5b785eb0535925559a12d18ff94b3b8b0c2a which sought to resolve this error on shallow repos, and introduced a bug of `/github/home/.local/share/dorothy/commands/git-helper: line 1211: rebase: unbound variable`

here is what the diverged/shallow bug looked like:

```
┌  Update Dorothy  ┐
┌  Ensure required dependencies  ┐
└  Ensure required dependencies  ┘
┌  Syncing the Dorothy installation at /Users/balupton/.local/share/dorothy  ┐
Fetched /Users/balupton/.local/share/dorothy remote = origin
Pulling /Users/balupton/.local/share/dorothy remote = origin branch = master
< git pull origin master >
From github.com:bevry/dorothy
 * branch              master     -> FETCH_HEAD
hint: Diverging branches can't be fast-forwarded, you need to either:
hint:
hint: 	git merge --no-ff
hint:
hint: or:
hint:
hint: 	git rebase
hint:
hint: Disable this message with "git config set advice.diverging false"
fatal: Not possible to fast-forward, aborting.
</ git pull origin master >[128]
Failed to pull /Users/balupton/.local/share/dorothy remote = origin branch = master
ERROR: Dorothy was unable to be automatically updated. Update Dorothy manually then try again.
```