purge sshfs
it's deprecated: https://github.com/libfuse/sshfs

fix:

```
Warning: sshfs has been deprecated because it has an archived upstream repository!
sshfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: sshfs: Unsatisfied requirements failed this build.
```